# Generated by Django 5.2.5 on 2025-10-11 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0002_center_constituency_center_polling_station_name_and_more"),
        ("squads", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="squad",
            name="registration_center",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated registration center for this squad",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="squads",
                to="centers.center",
            ),
        ),
    ]
