# Generated by Django 5.2.5 on 2025-10-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squads", "0003_squad_registration_center"),
    ]

    operations = [
        migrations.AlterField(
            model_name="squad",
            name="goal_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of members allowed in the squad",
                null=True,
            ),
        ),
    ]
