# Generated by Django 5.2.5 on 2025-10-11 22:22

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("squads", "0004_alter_squad_goal_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="squad",
            name="voter_registration_date",
            field=models.DateField(
                default=timezone.now,
                help_text="Date when squad members should register to vote",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="squadmember",
            name="has_registered",
            field=models.BooleanField(
                default=False, help_text="Whether this member has registered to vote"
            ),
        ),
    ]
