# Generated by Django 5.2.5 on 2025-10-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squads", "0005_squad_voter_registration_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="squad",
            old_name="goal_count",
            new_name="max_members",
        ),
    ]
