# Generated by Django 5.2.5 on 2025-10-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squads", "0006_rename_goal_count_squad_max_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="squad",
            name="voter_registration_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Date when squad members should register to vote",
                null=True,
            ),
        ),
    ]
