# Generated by Django 5.2.5 on 2025-10-11 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("squads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="squad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="squads.squad",
            ),
        ),
        migrations.AddField(
            model_name="eventrsvp",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rsvps",
                to="events.event",
            ),
        ),
    ]
