# Generated by Django 5.2.5 on 2025-10-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
