# Generated by Django 5.2.5 on 2025-10-11 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("county", models.CharField(max_length=50)),
                ("address", models.TextField()),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                (
                    "opening_hours",
                    models.JSONField(
                        blank=True, help_text="Store opening hours as JSON", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["county", "name"],
            },
        ),
    ]
