# Generated by Django 5.2.5 on 2025-10-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="constituency",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="center",
            name="polling_station_name",
            field=models.CharField(
                blank=True,
                help_text="Primary school or polling station name",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="ward",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
