# Generated by Django 5.2.5 on 2025-10-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0002_center_constituency_center_polling_station_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="location",
            field=models.CharField(
                blank=True, help_text="Ward or location name", max_length=200, null=True
            ),
        ),
    ]
